# -*- coding: utf-8 -*-
"""Interpretability Scores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jeBnQSEXrldAiQt1Bs71IT4vgNdFGG6g

# Import Interpretability CSV
"""

import pandas as pd

csv_file_path = '/content/Q&A Dataset - Interpretability_Dataset.csv'

df = pd.read_csv(csv_file_path)

df.head()

df['LLM #1: ChatGPT Generation'] = df['LLM #1: ChatGPT Generation'].astype(str)
df['LLM #2: Claude Generation'] = df['LLM #2: Claude Generation'].astype(str)

"""# Lexical Diversity"""

pip install lexical-diversity

from lexical_diversity import lex_div as ld
import spacy

"""## Pre-process texts using Lemmatizer (spaCy)"""

lemma = spacy.load('en_core_web_sm')

def lemmatize(sentence):
  """
  Lemmatize a sentence
  Input: raw sentencen
  Returns: array of lemmatized tokens
  """

  doc = lemma(sentence)

  lemmatized_tokens = [token.lemma_ for token in doc]

  return lemmatized_tokens

"""## Lemmatize + calc lexical diverisity"""

def lexical_diversity_score(sentence):
  lemmatized_tokens = lemmatize(sentence)

  score = ld.ttr(lemmatized_tokens)

  return score

lexical_diversity_score("the cat is happy is cat is happy")

"""## Calc LD Score on Dataset"""

df['ChatGPT LD Score'] = df['LLM #1: ChatGPT Generation'].apply(lexical_diversity_score)

df['Claude LD Score'] = df['LLM #2: Claude Generation'].apply(lexical_diversity_score)

df.head()

average_scores_chatGPT = df.groupby('Practice Area')['ChatGPT LD Score'].mean()

print("\nAverage LD Scores for Each Practice Area:")
print(average_scores_chatGPT)

average_scores_claude = df.groupby('Practice Area')['Claude LD Score'].mean()


print("\nAverage LD Scores for Each Practice Area:")
print(average_scores_claude)

df.to_csv('LD results.csv', index=False)

